// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package pgdb

type Country struct {
	ID      int32   `db:"id" json:"id"`
	Title   string  `db:"title" json:"title"`
	Code    string  `db:"code" json:"code"`
	IsoCode *string `db:"iso_code" json:"iso_code"`
}
