// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: mutations.sql

package pgdb

import (
	"context"
)

const CountryInsert = `-- name: CountryInsert :one
insert into countries (title, code, iso_code)
values ($1, $2, $3)
returning id, title, code, iso_code
`

type CountryInsertParams struct {
	Title   string  `db:"title" json:"title"`
	Code    string  `db:"code" json:"code"`
	IsoCode *string `db:"iso_code" json:"iso_code"`
}

func (q *Queries) CountryInsert(ctx context.Context, arg CountryInsertParams) (*Country, error) {
	row := q.db.QueryRow(ctx, CountryInsert, arg.Title, arg.Code, arg.IsoCode)
	var i Country
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Code,
		&i.IsoCode,
	)
	return &i, err
}

const CountryUpdate = `-- name: CountryUpdate :one
update countries
set title = $1, code = $2, iso_code = $3
where id = $4
returning id, title, code, iso_code
`

type CountryUpdateParams struct {
	Title   string  `db:"title" json:"title"`
	Code    string  `db:"code" json:"code"`
	IsoCode *string `db:"iso_code" json:"iso_code"`
	ID      int32   `db:"id" json:"id"`
}

func (q *Queries) CountryUpdate(ctx context.Context, arg CountryUpdateParams) (*Country, error) {
	row := q.db.QueryRow(ctx, CountryUpdate,
		arg.Title,
		arg.Code,
		arg.IsoCode,
		arg.ID,
	)
	var i Country
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Code,
		&i.IsoCode,
	)
	return &i, err
}
