// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package pgdb

import (
	"context"
)

type Querier interface {
	Countries(ctx context.Context) ([]*Country, error)
	CountryInsert(ctx context.Context, arg CountryInsertParams) (*Country, error)
	CountryOne(ctx context.Context, id int32) (*Country, error)
	CountryUpdate(ctx context.Context, arg CountryUpdateParams) (*Country, error)
}

var _ Querier = (*Queries)(nil)
