// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package pgdb

import (
	"context"
)

const Countries = `-- name: Countries :many
SELECT id, title, code, iso_code
FROM countries
ORDER BY id
`

func (q *Queries) Countries(ctx context.Context) ([]*Country, error) {
	rows, err := q.db.Query(ctx, Countries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Country{}
	for rows.Next() {
		var i Country
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Code,
			&i.IsoCode,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const CountryOne = `-- name: CountryOne :one
SELECT id, title, code, iso_code
FROM countries
where id = $1
`

func (q *Queries) CountryOne(ctx context.Context, id int32) (*Country, error) {
	row := q.db.QueryRow(ctx, CountryOne, id)
	var i Country
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Code,
		&i.IsoCode,
	)
	return &i, err
}
