// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: service.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ServicePB_Login_FullMethodName       = "/api.proto.ServicePB/Login"
	ServicePB_Countries_FullMethodName   = "/api.proto.ServicePB/Countries"
	ServicePB_CountryAdd_FullMethodName  = "/api.proto.ServicePB/CountryAdd"
	ServicePB_CountrySave_FullMethodName = "/api.proto.ServicePB/CountrySave"
)

// ServicePBClient is the client API for ServicePB service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ServicePBClient interface {
	Login(ctx context.Context, in *LoginIN, opts ...grpc.CallOption) (*LoginOUT, error)
	Countries(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*CountriesOUT, error)
	CountryAdd(ctx context.Context, in *CountryIN, opts ...grpc.CallOption) (*Country, error)
	CountrySave(ctx context.Context, in *Country, opts ...grpc.CallOption) (*Country, error)
}

type servicePBClient struct {
	cc grpc.ClientConnInterface
}

func NewServicePBClient(cc grpc.ClientConnInterface) ServicePBClient {
	return &servicePBClient{cc}
}

func (c *servicePBClient) Login(ctx context.Context, in *LoginIN, opts ...grpc.CallOption) (*LoginOUT, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginOUT)
	err := c.cc.Invoke(ctx, ServicePB_Login_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *servicePBClient) Countries(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*CountriesOUT, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CountriesOUT)
	err := c.cc.Invoke(ctx, ServicePB_Countries_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *servicePBClient) CountryAdd(ctx context.Context, in *CountryIN, opts ...grpc.CallOption) (*Country, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Country)
	err := c.cc.Invoke(ctx, ServicePB_CountryAdd_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *servicePBClient) CountrySave(ctx context.Context, in *Country, opts ...grpc.CallOption) (*Country, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Country)
	err := c.cc.Invoke(ctx, ServicePB_CountrySave_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServicePBServer is the server API for ServicePB service.
// All implementations must embed UnimplementedServicePBServer
// for forward compatibility.
type ServicePBServer interface {
	Login(context.Context, *LoginIN) (*LoginOUT, error)
	Countries(context.Context, *emptypb.Empty) (*CountriesOUT, error)
	CountryAdd(context.Context, *CountryIN) (*Country, error)
	CountrySave(context.Context, *Country) (*Country, error)
	mustEmbedUnimplementedServicePBServer()
}

// UnimplementedServicePBServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedServicePBServer struct{}

func (UnimplementedServicePBServer) Login(context.Context, *LoginIN) (*LoginOUT, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedServicePBServer) Countries(context.Context, *emptypb.Empty) (*CountriesOUT, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Countries not implemented")
}
func (UnimplementedServicePBServer) CountryAdd(context.Context, *CountryIN) (*Country, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CountryAdd not implemented")
}
func (UnimplementedServicePBServer) CountrySave(context.Context, *Country) (*Country, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CountrySave not implemented")
}
func (UnimplementedServicePBServer) mustEmbedUnimplementedServicePBServer() {}
func (UnimplementedServicePBServer) testEmbeddedByValue()                   {}

// UnsafeServicePBServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServicePBServer will
// result in compilation errors.
type UnsafeServicePBServer interface {
	mustEmbedUnimplementedServicePBServer()
}

func RegisterServicePBServer(s grpc.ServiceRegistrar, srv ServicePBServer) {
	// If the following call pancis, it indicates UnimplementedServicePBServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ServicePB_ServiceDesc, srv)
}

func _ServicePB_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginIN)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServicePBServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServicePB_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServicePBServer).Login(ctx, req.(*LoginIN))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServicePB_Countries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServicePBServer).Countries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServicePB_Countries_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServicePBServer).Countries(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServicePB_CountryAdd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CountryIN)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServicePBServer).CountryAdd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServicePB_CountryAdd_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServicePBServer).CountryAdd(ctx, req.(*CountryIN))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServicePB_CountrySave_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Country)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServicePBServer).CountrySave(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServicePB_CountrySave_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServicePBServer).CountrySave(ctx, req.(*Country))
	}
	return interceptor(ctx, in, info, handler)
}

// ServicePB_ServiceDesc is the grpc.ServiceDesc for ServicePB service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ServicePB_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.proto.ServicePB",
	HandlerType: (*ServicePBServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _ServicePB_Login_Handler,
		},
		{
			MethodName: "Countries",
			Handler:    _ServicePB_Countries_Handler,
		},
		{
			MethodName: "CountryAdd",
			Handler:    _ServicePB_CountryAdd_Handler,
		},
		{
			MethodName: "CountrySave",
			Handler:    _ServicePB_CountrySave_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
