// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: service.proto

package pb

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_service_proto protoreflect.FileDescriptor

const file_service_proto_rawDesc = "" +
	"\n" +
	"\rservice.proto\x12\tapi.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cgoogle/api/annotations.proto\x1a\rmessage.proto2\xda\x02\n" +
	"\tServicePB\x12L\n" +
	"\x05Login\x12\x12.api.proto.LoginIN\x1a\x13.api.proto.LoginOUT\"\x1a\x92A\x02b\x00\x82\xd3\xe4\x93\x02\x0f:\x01*\"\n" +
	"/api/login\x12Y\n" +
	"\tCountries\x12\x16.google.protobuf.Empty\x1a\x17.api.proto.CountriesOUT\"\x1b\x92A\x02b\x00\x82\xd3\xe4\x93\x02\x10\x12\x0e/api/countries\x12O\n" +
	"\n" +
	"CountryAdd\x12\x14.api.proto.CountryIN\x1a\x12.api.proto.Country\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/api/country\x12S\n" +
	"\vCountrySave\x12\x12.api.proto.Country\x1a\x12.api.proto.Country\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\x1a\x11/api/country/{id}B\xe7\x01\x92A\xd8\x01\x12X\n" +
	"\x16Voita.PRO template API\"9\n" +
	"\vDevelopment\x12*https://github.com/voita-pro/http-grpc-api2\x031.0*\x01\x012\x10application/jsonZY\n" +
	"W\n" +
	"\x06Bearer\x12M\b\x02\x128Authentication token, prefixed by Bearer: Bearer {token}\x1a\rAuthorization \x02b\f\n" +
	"\n" +
	"\n" +
	"\x06Bearer\x12\x00Z\tpkg/pb;pbb\x06proto3"

var file_service_proto_goTypes = []any{
	(*LoginIN)(nil),       // 0: api.proto.LoginIN
	(*emptypb.Empty)(nil), // 1: google.protobuf.Empty
	(*CountryIN)(nil),     // 2: api.proto.CountryIN
	(*Country)(nil),       // 3: api.proto.Country
	(*LoginOUT)(nil),      // 4: api.proto.LoginOUT
	(*CountriesOUT)(nil),  // 5: api.proto.CountriesOUT
}
var file_service_proto_depIdxs = []int32{
	0, // 0: api.proto.ServicePB.Login:input_type -> api.proto.LoginIN
	1, // 1: api.proto.ServicePB.Countries:input_type -> google.protobuf.Empty
	2, // 2: api.proto.ServicePB.CountryAdd:input_type -> api.proto.CountryIN
	3, // 3: api.proto.ServicePB.CountrySave:input_type -> api.proto.Country
	4, // 4: api.proto.ServicePB.Login:output_type -> api.proto.LoginOUT
	5, // 5: api.proto.ServicePB.Countries:output_type -> api.proto.CountriesOUT
	3, // 6: api.proto.ServicePB.CountryAdd:output_type -> api.proto.Country
	3, // 7: api.proto.ServicePB.CountrySave:output_type -> api.proto.Country
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_service_proto_init() }
func file_service_proto_init() {
	if File_service_proto != nil {
		return
	}
	file_message_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_proto_goTypes,
		DependencyIndexes: file_service_proto_depIdxs,
	}.Build()
	File_service_proto = out.File
	file_service_proto_goTypes = nil
	file_service_proto_depIdxs = nil
}
